name: mongiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  
  # State Management & Storage
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  
  # UI Assets
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OmarBold
      fonts:
        - asset: assets/fonts/Omar-Bold-1.ttf
    - family: OmarRegular
      fonts:
        - asset: assets/fonts/Omar-Regular-1.ttf
    - family: OmarLight
      fonts:
        - asset: assets/fonts/Omar-Light-1.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ast.png"
  min_sdk_android: 21
